function entries = prepareStressReportEntries(stresses)
%PREPARESTRESSREPORTENTRIES Build formatted stress report lines and metadata.

    bending_summary = computeBendingExtremaSummary(stresses);
    shear_summary = computeShearExtremaSummary(stresses);
    von_mises_summary = computeVonMisesExtremaSummary(stresses);

    entries = struct();

    entries.maxBendingMoment = buildEntry('Maximum bending moment:', ...
        bending_summary.moment.value, 'N·m', ...
        bending_summary.moment.elementID, ...
        bending_summary.moment.planeIdx, ...
        bending_summary.moment.endIdx);

    plane1_summary = bending_summary.stressPlane(1);
    entries.maxBendingStressPlane1 = buildEntry('Maximum bending stress (Plane 1):', ...
        plane1_summary.value, 'Pa', ...
        plane1_summary.elementID, ...
        plane1_summary.planeIdx, ...
        plane1_summary.endIdx);

    plane2_idx = min(numel(bending_summary.stressPlane), 2);
    plane2_summary = bending_summary.stressPlane(plane2_idx);
    entries.maxBendingStressPlane2 = buildEntry('Maximum bending stress (Plane 2):', ...
        plane2_summary.value, 'Pa', ...
        plane2_summary.elementID, ...
        plane2_summary.planeIdx, ...
        plane2_summary.endIdx);

    entries.maxBendingStressEnvelope = buildEntry('Maximum bending stress (Envelope):', ...
        bending_summary.stressEnvelope.value, 'Pa', ...
        bending_summary.stressEnvelope.elementID, ...
        bending_summary.stressEnvelope.planeIdx, ...
        bending_summary.stressEnvelope.endIdx);

    entries.maxShearForce = buildEntry('Maximum shear force:', ...
        shear_summary.force.value, 'N', ...
        shear_summary.force.elementID, ...
        shear_summary.force.planeIdx, ...
        shear_summary.force.endIdx);

    entries.maxShearStress = buildEntry('Maximum shear stress:', ...
        shear_summary.stress.value, 'Pa', ...
        shear_summary.stress.elementID, ...
        shear_summary.stress.planeIdx, ...
        shear_summary.stress.endIdx);

    entries.maxVonMisesStress = buildEntry('Maximum von Mises stress:', ...
        von_mises_summary.value, 'Pa', ...
        von_mises_summary.elementID, ...
        von_mises_summary.planeIdx, ...
        von_mises_summary.endIdx);
end

function entry = buildEntry(label, value, units, elementID, planeIdx, endIdx)
%BUILDENTRY Standardize report entry representation for console reporting.

    if nargin < 6
        error('buildEntry requires label, value, units, elementID, planeIdx, and endIdx.');
    end

    if isnan(elementID)
        elementID = 0;
    end

    planeIdx = clampIndex(planeIdx, 2);
    endIdx = clampIndex(endIdx, 2);

    endChar = char('A' + (endIdx - 1));

    if isnan(value)
        value = 0;
    end
    value = abs(value);

    entry = struct();
    entry.label = label;
    entry.value = value;
    entry.units = units;
    entry.loc = struct('elem', elementID, 'plane', planeIdx, 'end', endChar);
    entry.text = sprintf('%s %.6e %s (Element %d, Plane %d, End %s)', ...
        label, value, units, elementID, planeIdx, endChar);
end

function idx = clampIndex(idx, upper)
%CLAMPINDEX Ensure indices fall within valid reporting bounds.

    if isnan(idx) || idx < 1
        idx = 1;
    elseif idx > upper
        idx = upper;
    end
end
